services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-app:latest
    container_name: express-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - .env
    networks:
      - my-network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:${PORT:-3000}/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

networks:
  my-network:
    driver: bridge
